DROP DATABASE IF EXISTS IGBot;
CREATE DATABASE IGBot;

use IGBot;

CREATE TABLE player (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  discord_id VARCHAR(30) NOT NULL,
  island VARCHAR(30) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE bourse (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  day DATETIME NOT NULL,
  value INT NOT NULL,
  player_id INT NOT NULL,
  CONSTRAINT discord_id_fk FOREIGN KEY (player_id) REFERENCES player (id)
) ENGINE=InnoDB;
